version: '3'

networks:
    web:
        external: true
    internal:
        external: false

services:
    carpentierpro:
        build: .
        labels:
          - traefik.backend=simplekanban
          - traefik.frontend.rule=Host:kanban.carpentier.pro
          - traefik.docker.network=web
          - traefik.enable=true
        networks:
          - internal
          - web
        restart: always